[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "1.1.0"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "0.10.1"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.5"
